### ISSUE TITLE
Clean up emacs config

### ISSUE THREAD

**Issue by benreyn** [breyno127/dotfiles#16]
I need to come up with some way to clean up my emacs configuration. I can either start working on #1 or just break things out into more files.

Another approach might be a combination of the two, following the example from [`iqbalansari/dotEmacs`](https://github.com/iqbalansari/dotEmacs), (which has a ton of other cool emacs configuration I should look at anyway.

**Comment by benreyn** [comment]
Getting dangerously close to trying out [spacemacs](https://github.com/syl20bnr/spacemacs) as an alternative to this.

**Comment by bdavi** [comment]
I thought you were philosophically opposed to spacemacs. I'm just asking for some intellectual consistency here.

**Comment by benreyn** [comment]
But it looks SOOOO nice Brian!

**Comment by benreyn** [comment]
Closing this because Im using spacemacs now.
